// <auto-generated />
namespace PostFeed.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddatabasegeneratedKeysforAuthorandPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddatabasegeneratedKeysforAuthorandPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201608110312049_added database generated Keys for Author and Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
